/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entity.Messages;
import entity.Tasks;
import entity.Users;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;
import javax.persistence.TypedQuery;
import services.ApplicationController;

/**
 *
 * @author Cherry
 */
public class ProjectTaskDetailPanel extends javax.swing.JPanel {
    
    private Tasks task;

    /**
     * Creates new form java
     */
    public ProjectTaskDetailPanel(Tasks task) {
        this.task = task;
        initComponents();
        textTitle.setText(task.getTaskName());
        // get taskowner name with join query from task's owner id and user in user table
        int ownerId = task.getOwnerId();
        EntityManager em = ApplicationController.getEnitityManager();
        TypedQuery<Users> queryUserById = (TypedQuery<Users>) em.createNamedQuery("Users.findById");
        Users taskOwner = queryUserById.setParameter("id", ownerId).getSingleResult();
        String ownerName = taskOwner.getFirstName();
        textOwner.setText(ownerName);
        textDescription.setText(task.getDescription());//check whether will change line
        
        textTitle.setEditable(false);
        textOwner.setEditable(false);
        textDescription.setEditable(false);
        textComments.setEditable(false);
        reloadComments();
        
        buttonComment.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                Messages m = new Messages();
                m.setTaskId(task.getId());
                m.setContent(textComment.getText());
                m.setSenderId(14); // TODO change to user id
                m.setCreatedAt(new Date());
                EntityTransaction transaction = ApplicationController.getEnitityManager().getTransaction();
                transaction.begin();
                ApplicationController.getEnitityManager().persist(m);
                transaction.commit();
                reloadComments();
            }
        });
    }
    
    private void reloadComments() {
        textComments.setContentType("text/html");
        StringBuilder html = new StringBuilder("<html>");
        EntityManager em = ApplicationController.getEnitityManager();
        TypedQuery<Messages> query = (TypedQuery<Messages>) em.createNamedQuery("Messages.findByTaskId");
        TypedQuery<Users> queryUser = (TypedQuery<Users>) em.createNamedQuery("Users.findById");
        List<Messages> messages = query.setParameter("taskId",task.getId()).getResultList();
        for (Messages m : messages) {
            Users users = queryUser.setParameter("id", m.getSenderId()).getSingleResult();
            html.append("<span color='gray'>(").append(m.getCreatedAt().toString()).append(") </span>");
            html.append("<span color='green'><b>").append(users.getFirstName()).append("</b></span>");
            html.append(": ").append(m.getContent()).append("<br />");
        }
        html.append("</ul></html>");
        textComments.setText(html.toString());
        textComments.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textTitle = new java.awt.TextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        textComment = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textComments = new javax.swing.JTextPane();
        buttonComment = new javax.swing.JButton();
        textOwner = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        textDescription = new javax.swing.JTextArea();

        jScrollPane1.setViewportView(jTextPane1);

        setPreferredSize(new java.awt.Dimension(900, 426));
        setLayout(null);

        jLabel1.setText("Title:");
        add(jLabel1);
        jLabel1.setBounds(6, 10, 32, 16);

        jLabel2.setText("Description:");
        add(jLabel2);
        jLabel2.setBounds(6, 74, 77, 16);

        jLabel3.setText("Owner:");
        add(jLabel3);
        jLabel3.setBounds(6, 40, 44, 16);
        add(textTitle);
        textTitle.setBounds(100, 10, 790, 20);

        textComment.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setViewportView(textComment);

        add(jScrollPane2);
        jScrollPane2.setBounds(6, 391, 783, 29);

        jLabel4.setText("History:");
        add(jLabel4);
        jLabel4.setBounds(6, 154, 50, 16);

        textComments.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane3.setViewportView(textComments);

        add(jScrollPane3);
        jScrollPane3.setBounds(6, 178, 888, 200);

        buttonComment.setText("Comment");
        add(buttonComment);
        buttonComment.setBounds(795, 391, 95, 29);
        add(textOwner);
        textOwner.setBounds(100, 40, 790, 28);

        textDescription.setColumns(20);
        textDescription.setRows(5);
        jScrollPane4.setViewportView(textDescription);

        add(jScrollPane4);
        jScrollPane4.setBounds(101, 74, 789, 84);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonComment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane textComment;
    private javax.swing.JTextPane textComments;
    private javax.swing.JTextArea textDescription;
    private javax.swing.JTextField textOwner;
    private java.awt.TextField textTitle;
    // End of variables declaration//GEN-END:variables
}
