/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entity.Messages;
import entity.Projects;
import entity.Tasks;
import entity.Users;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import model.ProjectMemberTableModel;
import services.ApplicationController;

/**
 *
 * @author Cherry
 */
public class ProjectInfoPanel extends javax.swing.JPanel {

    private Projects project;
    /**
     * Creates new form ProjectInfoPanel
     */
    public ProjectInfoPanel() {
        initComponents();
        project = ApplicationController.getCurrentProject();
        textUpdates.setContentType("text/html");
        StringBuilder html = new StringBuilder("<html>");
        EntityManager em = ApplicationController.getEnitityManager();
        TypedQuery<Tasks> query = (TypedQuery<Tasks>) em.createNamedQuery("Tasks.findByProjectId");
        List<Tasks> tasks = query.setParameter("projectId", project.getId()).getResultList();
        for (Tasks t : tasks) {
            if (!"closed".equals(t.getStatus()) || t.getOwnerId() == null) {
                continue;
            }
            TypedQuery<Users> queryOwner = (TypedQuery<Users>) em.createNamedQuery("Users.findById");
            Users u = queryOwner.setParameter("id", t.getOwnerId()).getSingleResult();
            html.append("<span color='gray'>(").append(t.getClosedAt().toString()).append(") </span>");
            html.append("<span color='green'><b>").append(u.getFirstName()).append("</b></span> finished task ");
            html.append("#").append(t.getId()).append(": ").append(t.getTaskName()).append("<br />");
        }
        html.append("</ul></html>");
        textUpdates.setText(html.toString());
        textUpdates.repaint();

        TypedQuery<Users> queryPM = (TypedQuery<Users>) em.createNamedQuery("Users.findById");
        Users pm = queryPM.setParameter("id", project.getPmId()).getSingleResult();
        textPM.setText(pm.getFirstName() + " " + pm.getLastName());
        tableMembers.setModel(new ProjectMemberTableModel(project));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textUpdates = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        textDescription = new javax.swing.JTextField();
        textPM = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMembers = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Project Name");

        jLabel2.setText("Project Manager");

        jLabel3.setText("Team Members");

        jLabel4.setText("Recent Updates");

        jScrollPane2.setViewportView(textUpdates);

        jLabel5.setText("Description");

        textDescription.setBorder(null);

        textPM.setBorder(null);

        tableMembers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableMembers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1017, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                                    .addComponent(textPM, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addComponent(jLabel4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(textDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textPM, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableMembers;
    private javax.swing.JTextField textDescription;
    private javax.swing.JTextField textPM;
    private javax.swing.JTextPane textUpdates;
    // End of variables declaration//GEN-END:variables
}
