/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entity.Projects;
import entity.Tasks;
import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.ScrollPane;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import services.Application;

/**
 *
 * @author Cherry
 */
public class ProjectTaskPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProjectTaskPanel
     */
    private JTable taskList;
    private JScrollPane scrollPane;
    
    public ProjectTaskPanel() {
        initComponents();
        fetchData();
    }
    
    private void fetchData() {
    //get data from db and show on table;
        String colNames[] = {"Task ID", "Task Name", "Task Owner", "Due day", "Updated Time"};
        //String[][] data = new String[4][4];
        
        // fetch data from db tasks
        //Tasks tasks = new Tasks(1);
        EntityManager em = Application.getEnitityManager();
        System.out.println(em);
        em.getTransaction().begin();
        //TypedQuery<Projects> queryProById = (TypedQuery<Projects>) em.createNamedQuery("Projects.findById");
        TypedQuery<Projects> queryProById = em.createQuery("SELECT p FROM Projects p", Projects.class);
        //Query queryProById = em.createNamedQuery("findById");
        Integer proId = 1;
//        Projects pro = queryProById.setParameter("id", proId).getResultList().get(0);
        Projects pro = queryProById.getResultList().get(0);
        Set<Tasks> tasks = pro.getTasks();
        int size = tasks.size();
        String [][] data= new String[size][5];
        int count = 0;
        for(Tasks task: tasks) {
            data[count][0] = Integer.toString(count - 1);
            data[count][1] = task.getTaskName();
            data[count][2] = "1";
            data[count][3] = "ddd";
            data[count][4] = "ddc";
            count++;
        }
        
        
//        String [][] data= new String[][]{
//            {"1","Task1", "cherry","Dec 2014", "Nov 30"},
//            {"2", "Task1", "cherry","Dec 2014", "Nov 30"},
//            {"3", "Task1", "cherry","Dec 2014", "Nov 30"},
//            {"4", "Task1", "cherry","Dec 2014", "Nov 30"}
//        };
        taskList = new JTable(data, colNames);
        showTable();
    }
    
    private void showTable() {
        scrollPane = new JScrollPane(taskList);
        taskList.setSize(900, 900);
        scrollPane.setSize(300, 300);
        this.add(scrollPane);
        revalidate();
        scrollPane.repaint();
        this.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        jButton1.setText("Add Task");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(663, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(120, 120, 120))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(400, 400, 400))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // switch to createtaskPanel
        MainAppFrame jf = Application.getMainFrame();
        JPanel newP = new CreateTasksPanel();
        newP.setSize(1000, 1000);
        //newP.add(new Button("test panel"));
        newP.setVisible(true);
        jf.switchPanel(newP);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
